version: "3.7"

x-api-common: &api-common
  image: ghcr.io/openfoodfacts/nutripatrol/api:${TAG:-dev}
  restart: ${RESTART_POLICY}
  environment:
    - SENTRY_DNS
    - LOG_LEVEL
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - POSTGRES_HOST
  networks:
    - default

services:
  api:
    <<: *api-common
    ports:
      - "${API_EXPOSE:-127.0.0.1:8000}:8000"

  postgres:
    restart: $RESTART_POLICY
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=1024MB -c work_mem=64MB
    mem_limit: 4g
    shm_size: 1g
    ports:
      - "${POSTGRES_EXPOSE:-127.0.0.1:5432}:5432"

volumes:
  postgres-data: